<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2PzDai\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2PzDai/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC2PzDai.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC2PzDai\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC2PzDai\App_KernelDevDebugContainer([
    'container.build_hash' => 'C2PzDai',
    'container.build_id' => '0a6080fe',
    'container.build_time' => 1719165088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2PzDai');
